api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: traefik-public
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@rifuki.dev
      storage: /letsencrypt/acme.json
      tlsChallenge: {}

log:
  level: INFO

accessLog: {}
